# Generated by Django 3.1.3 on 2020-11-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('total_result', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('link', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='search_engine.query')),
            ],
        ),
    ]
