# Generated by Django 3.1.3 on 2020-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
