# Generated by Django 3.1.3 on 2020-11-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20201128_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='total_result',
            field=models.BigIntegerField(default=0),
        ),
    ]
