# Generated by Django 3.1.3 on 2020-11-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20201129_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='client_ip',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
